query me {
    me {
        id
        email
        first_name
        last_name,
        stripe_subscription_info {
            status
            expiry_date
        }
    }
}

query allCourseProgress {
    all_course_progress {
        id
        user_id
        unit_slug
        course_slug
        status
        updated_at
    }
}

query customerPortalUrl($return_url: String!) {
    me {
        customer_portal_url(return_url: $return_url)
    }
}

mutation createLuminaUniversityCheckoutSession($return_url: String!) {
    create_light_university_checkout_session(success_url: $return_url)
}

query getCourseProgress($course_slug: String!) {
    course_progress(course_slug: $course_slug) {
        id
        status
        user_id
        unit_slug
        course_slug
        updated_at
    }
}


mutation setUnitProgress($course_slug: String!, $unit_slug: String!, $status: UnitStatus!) {
    set_unit_progress(course_slug: $course_slug, unit_slug: $unit_slug, status: $status) {
        id
    }
}

mutation SetQuestionAssessment(
    $question: String!
    $answer: String!
    $course_slug: String!
    $unit_slug: String!
    $question_slug: String!
    $context: String
) {
    question_assessment(
        question: $question
        answer: $answer
        course_slug: $course_slug
        unit_slug: $unit_slug
        question_slug: $question_slug,
        question_context: $context
    ) {
        feedback
        assessment
    }
}

query GetQuestionAssessment(
    $course_slug: String!
    $unit_slug: String!
    $question_slug: String!
) {
    question_assessment(
        course_slug: $course_slug
        unit_slug: $unit_slug
        question_slug: $question_slug
    ) {
        feedback
        answer
        assessment
    }
}